[package]
name = "ygharsallah/replication"
description = "does something!"
license = "MIT"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml"]

[dependencies]
